# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-09 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.upload_file_path),
        ),
    ]
