# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-28 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_products_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(default='abc'),
        ),
    ]
