# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-31 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20180529_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to=products.models.upload_file_path)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=products.models.upload_file_path)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=products.models.upload_file_path)),
            ],
        ),
    ]
