# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-17 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_background'),
    ]

    operations = [
        migrations.DeleteModel(
            name='background',
        ),
    ]
